Fix SAPIC for OCaml 4.12
List.compare shadows Stdlib.compare since 4.12, which breaks SAPIC with the following errors:

```
File "position.ml", line 9, characters 32-33:
9 |     (a::ar,b::br) -> if compare a b = 0 then compare ar br else compare a b
                                    ^
Error: This expression has type int but an expression was expected of type
         'a -> 'a -> int
```

```
File "var.ml", line 32, characters 28-36:
32 |         | (a,b)  -> compare (rank a) (rank b)
                                 ^^^^^^^^
Error: This expression has type int but an expression was expected of type
         'a -> 'a -> int
```

This PR refers to Stdlib explicitly which fixes the build, but raises minimum required version of OCaml to 4.07.

For more info, please refer to the upstream PR: https://github.com/ocaml/ocaml/pull/9668